name: DockRay
version: 0.0.1
summary: Docker manager.
description: A docker manager with soft use.

confinement: strict
base: core18
grade: stable

slots:
  dbus-DockRay: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: org.bar.DockRay # adjust accordingly to your app name and
    
apps:
  DockRay:
    command: DockRay
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-DockRay
parts:
  DockRay:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
